'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Form_BienvenidoSD

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''formLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tipoCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipoCB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSec As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grupoCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grupoCB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divDep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDep As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbo_departamento1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_departamento1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbo_provincia1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_provincia1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divDis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDis As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divEnti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEnti As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''entidadCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents entidadCB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''nombreTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dniTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dniTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''correoTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents correoTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''telefonoTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents telefonoTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''generarB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents generarB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''listAcuerdoB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listAcuerdoB As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''listHitosB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listHitosB As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''validaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validaB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''registroAsistenciaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registroAsistenciaB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''asistenteListB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asistenteListB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''acreditaListB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acreditaListB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''importaAcreditadoB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents importaAcreditadoB As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenField As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SDS_SD_P_selectGrupos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_SD_P_selectGrupos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SDS_P_selectDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_P_selectDepartamento As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SDS_P_selectProvincia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_P_selectProvincia As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SDS_SD_P_selectEntidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_SD_P_selectEntidades As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
End Class
